import { useState, useEffect } from 'react';
import Head from 'next/head';
import {
  ChevronRight,
  ChevronLeft,
  CheckCircle2,
  Circle,
  Search,
  X,
  Menu,
  Home,
  Book,
  CheckSquare,
} from 'lucide-react';

const PRODUCTS_DATA = {
  'incredible-suds': {
    name: 'Incredible Suds',
    type: 'Surfactant Concentrate',
    purpose: 'Pre-wash foam cannon or contact wash soap',
    dilution: {
      foam: '1–2 oz per 30oz reservoir (~1000:1)',
      bucket: '½ oz per 3–4 gallons (15ml)',
    },
    application:
      'Creates protective wash surface to prevent swirls and scratching',
    coverage: 'Cuts through heavy dirt, road film, and grime',
    services: ['Exterior Detail', 'Maintenance Wash'],
  },
  'rinse-less-wash': {
    name: 'Rinse Less Wash',
    type: 'Concentrate with Lubricants',
    purpose: 'Final rinse replacement or touchless rinse alternative',
    dilution: '½ oz per gallon (4ml per liter / 256:1)',
    application: 'Applied after contact wash instead of water rinse',
    coverage: 'Safe for all surfaces',
    services: ['Exterior Detail', 'Maintenance Wash', 'Ceramic Coating Prep'],
  },
  'all-clean': {
    name: 'All Clean',
    type: 'Citrus-based All-Purpose Cleaner',
    purpose: 'All-purpose cleaner for interior and exterior',
    dilution: {
      exterior: '15:1 (water to concentrate)',
      interior: '30:1 (water to concentrate)',
    },
    application: 'Spray on microfiber, wipe dry and buff',
    coverage: 'Bugs, tires, wheels, engine, paint, plastic, glass',
    services: ['Interior Detail', 'Exterior Detail'],
  },
  'waterless-wash': {
    name: 'Waterless Wash',
    type: 'Ready to Use (RTU)',
    purpose: 'Dust and fingerprint removal, insect and bird bomb cleaning',
    application: 'Spray liberally, dwell, encapsulate with microfiber, buff dry',
    coverage: 'All exterior surfaces',
    services: ['Maintenance Wash'],
  },
  'iron-remover': {
    name: 'Iron Remover',
    type: 'pH-Neutral RTU',
    purpose: 'Remove ferrous oxide particles from paint',
    dilution: 'Ready to use',
    application:
      '1 spray on quad-fold towel + 1 spray on wet surface, agitate gently (NO PRESSURE), rinse',
    coverage: 'Paint, PPF, vinyl, matte paint, wheels',
    services: ['Exterior Detail', 'Ceramic Coating Prep', 'Paint Correction'],
  },
  'water-spot-remover': {
    name: 'Water Spot Remover',
    type: 'Ready to Use (RTU)',
    purpose: 'Remove dried water mineral deposits',
    dilution: 'Ready to use',
    application: 'Spray on panel, agitate with damp towel, 1–2 min dwell, rinse',
    coverage: 'Paint, interior, windows, wheels, tires',
    services: ['Exterior Detail', 'Ceramic Coating Prep'],
  },
  'tree-sap-remover': {
    name: 'Tree Sap Remover',
    type: 'Professional Solvent RTU',
    purpose: 'Remove stubborn road tar, tree sap, adhesive residue',
    dilution: 'Ready to use',
    application: 'Spray on microfiber, apply to area, let penetrate',
    coverage: 'Clear coat, most plastics, wheels',
    services: ['Exterior Detail', 'Odour Treatment'],
  },
  'panel-prep': {
    name: 'Panel Prep',
    type: 'Spray Cleaner',
    purpose: 'Remove grease and compound residue before ceramic coating',
    dilution: 'Ready to use',
    application: 'Spray on microfiber, wipe dry, buff',
    coverage: 'Paint, plastic, glass',
    services: ['Ceramic Coating Prep'],
  },
  'compound': {
    name: 'Gold Standard Compound',
    type: 'Gel Abrasive with Geodesic Technology',
    purpose: 'Aggressive cutting to remove oxidation and deep scratches',
    dilution: '3–4 drops on damp pad',
    application: 'Wool DA (speed 2–3) or Wool Rotary (speed 1), no pressure',
    coverage: 'Paint correction, oxidation removal',
    services: ['Paint Correction', 'Ceramic Coating Prep'],
  },
  'polish': {
    name: 'Gold Standard Polish',
    type: 'Fine Abrasive Polish',
    purpose: 'Final finishing, swirl removal, gloss enhancement',
    dilution: '1 spray on damp pad',
    application: 'Red Jewelling pad (DA 2–3, Rotary 1), low speed, no pressure',
    coverage: 'Paint finishing',
    services: ['Paint Correction', 'Ceramic Coating Prep'],
  },
  'app': {
    name: 'C6 APP (Adhesion Promoter Polish)',
    type: 'Specialized Polish',
    purpose: 'Prepare paint surface for ceramic coating adhesion',
    dilution: 'Not applicable (applied directly)',
    application:
      'Red Jewelling pad (DRY), 2–9mm stroke DA, wipe with dry microfiber as you go',
    coverage: 'Full paint panel prep',
    services: ['Ceramic Coating Prep'],
  },
  'hydr3': {
    name: 'DIY Detail 3 Year (Type 2)',
    type: 'TEOS-Based Ceramic Coating',
    purpose: 'Professional ceramic coating protection',
    dilution: 'Ready to use',
    application:
      'Foam applicator, several drops, circular motion, 2–5 min dwell, level at 50% clear trigger',
    coverage: 'Paint, PPF, vinyl, trim, chrome, wheels, windows',
    services: ['Ceramic Coating Prep'],
  },
  'hydr5': {
    name: 'DIY Detail 5 Year (Type 3)',
    type: 'TEOS-Based Ceramic Coating',
    purpose: 'Professional-grade ceramic coating protection',
    dilution: 'Ready to use',
    application:
      'Foam applicator, 8–10 drops prime, 1–2 drops per panel, 2–5 min dwell, level at 50% clear',
    coverage: 'Paint, PPF, vinyl, trim, chrome, wheels, windows',
    services: ['Ceramic Coating Prep'],
  },
  'hydr8': {
    name: 'HYDR8 (8-Year, Type 3)',
    type: 'TEOS-Based Pro-Grade Ceramic',
    purpose: '8-year professional coating with enhanced gloss',
    dilution: 'Ready to use',
    application:
      'Foam applicator, 8–10 drops prime, 1–2 drops per panel, full vehicle application allowed',
    coverage: 'Paint, PPF, vinyl, trim, chrome, wheels, windows, matte',
    services: ['Ceramic Coating Prep'],
  },
  'quick-beads': {
    name: 'Quick Beads',
    type: 'Graphene Ceramic Sealant RTU',
    purpose: 'Maintenance sealant with rapid activation',
    dilution: 'Ready to use',
    application: 'Spray on clean wet surface, activate with water pressure, rinse',
    coverage: 'All exterior paint surfaces',
    services: ['Maintenance Wash'],
  },
  'envie': {
    name: 'Envie',
    type: 'Ceramic Detail Spray Sealant RTU',
    purpose: 'Premium ceramic spray sealant for drying aid or quick detailer',
    dilution: 'Ready to use',
    application:
      'As drying aid: mist into towel during drying. As quick detailer: spray dry surface, buff.',
    coverage: 'Paint, plastic, metal, trim, glass, headlights',
    services: ['Maintenance Wash', 'Exterior Detail'],
  },
  'crystal-clear': {
    name: 'Crystal Clear',
    type: 'Glass Coating RTU',
    purpose: 'Professional glass clarity and protection',
    dilution: 'Ready to use',
    application: 'Spray on microfiber towel, wipe streak-free',
    coverage: 'Interior and exterior glass, tinted windows safe',
    services: ['Interior Detail'],
  },
  'tire-dressing': {
    name: 'Tire Dressing',
    type: 'Tire Shine RTU',
    purpose: 'Deep black finish with long-lasting shine',
    dilution: {
      exterior: 'As-is',
      interior:
